FIELD_LABELS = {
    'id': 'Image ID',
    'strip_id': 'Strip ID',
    'experiment_id': 'Experiment ID',
    'experiment_ids': 'Experiment IDs',
    'strip_count': 'Strip count',
    'select': 'Select',
    'remove': 'Remove',
    'Remove': 'Remove',
    'experiment_title': 'Experiment title',
    'experiment_date': 'Experiment date',
    'operator': 'Operator',
    'condition': 'Changed variable',
    'changed': 'Changed variable',
    'changed_field': 'Changed variable',
    'changed_value': 'Changed value',
    'condition_value': 'Changed value',
    'sample_equivalent_mg_ml': 'Sample equivalent (mg/mL)',
    'dilution_equivalent': 'Dilution equivalent',
    'nitrocellulose_material': 'Nitrocellulose membrane',
    'cassette': 'Cassette',
    'sample_pad_material': 'Sample pad',
    'sample_pad_pretreatment_lot': 'Sample pad pretreatment lot',
    'conjugate_pad_material': 'Conjugate pad',
    'conjugate_pad_pretreatment_lot': 'Conjugate pad pretreatment lot',
    'absorbent_pad_material': 'Absorbent pad',
    'running_buffer_lot': 'Running buffer lot',
    'glide_buffer_lot': 'Glide buffer lot',
    'reconstitution_buffer_lot': 'Reconstitution buffer lot',
    'test_line_reagent': 'Test line reagent',
    'test_line_concentration_mg_ml': 'Test line concentration (mg/mL)',
    'reference_line_reagent': 'Reference line reagent',
    'reference_line_concentration_mg_ml': 'Reference line concentration (mg/mL)',
    'line_gliding_date': 'Line gliding date',
    'line_storage_condition': 'Line storage condition',
    'line_drying_time': 'Line drying time',
    'glide_volume_ul_per_cm': 'Glide volume (uL/cm)',
    'conjugate_batch_name': 'Conjugate batch',
    'conjugate_ratio': 'Conjugate ratio',
    'reconstitution_volume_ul': 'Reconstitution volume (uL)',
    'gnp_lot': 'GNP lot',
    'conjugate_loading_ul_per_cm': 'Conjugate loading (uL/cm)',
    'drying_time': 'Drying time',
    'storage_condition': 'Storage condition',
    'stability_timepoint': 'Stability timepoint',
    'experiment_notes': 'Experiment notes',
    'manufacture_date': 'Manufacture date',
    'prepared_by': 'Prepared by',
    'active': 'Active',
    'lot_id': 'Lot ID',
    'lot_name': 'Lot name',
    'reagent_type': 'Reagent type',
    'pad_id': 'Pad ID',
    'pad_name': 'Pad name',
    'type': 'Type',
    'composition_details': 'Composition details',
    'notes': 'Notes',
    'test_line_raw_intensity': 'Test raw intensity',
    'reference_line_raw_intensity': 'Reference raw intensity',
    'test_line_corrected_intensity': 'Test corrected intensity',
    'reference_line_corrected_intensity': 'Reference corrected intensity',
    'c': 'Reference raw',
    't': 'Test raw',
    'raw_c': 'Reference raw',
    'raw_t': 'Test raw',
    'correct_c': 'Reference corrected',
    'correct_t': 'Test corrected',
    'test_reference_ratio': 'T/R ratio',
    'reference_test_ratio': 'R/T ratio',
    'ratio': 'T/R ratio',
    'ratio_num': 'T/R ratio',
    'ratio_group': 'Ratio group',
    'overall_membrane_background': 'Membrane background',
    'bg': 'Background',
    'bg_num': 'Background',
    'ct_bg_sum': 'Corrected total',
    'valid_strip': 'Valid strip',
    'failure_reason': 'Failure reason',
    'quality_flags': 'Quality flags',
    'image_filename': 'Image filename',
    'image_upload_datetime': 'Capture date/time',
    'image_upload_date': 'Capture date',
    'image_upload_time': 'Capture time',
    'date': 'Capture date',
    'time': 'Capture time',
    'image_name': 'Image name',
    'original_name': 'Original file',
    'original_path': 'Original image path',
    'gray_path': 'Grayscale path',
    'cropped_name': 'Cropped image',
    'cropped_path': 'Cropped path',
    'dark_regions_path': 'Dark regions path',
    'starred': 'Starred',
    'star': 'Star',
    'anomaly_flag': 'Anomaly',
    'source_file_kind': 'Source file',
    'capture_datetime': 'Capture date/time',
    'file_kind': 'Source file',
    'reviewer_id': 'Reviewer',
    'gray_avg': 'Mean gray value',
    'predicted_gray_avg': 'Predicted gray value',
    'corrected_gray_avg': 'Corrected gray value',
    'exp_component': 'Model component',
    'epsilon': 'Residual',
    'x_start': 'X start',
    'x_end': 'X end',
    'source_image': 'Source image',
    'saved_at': 'Saved at',
    'box_count': 'Box count',
    'competitive_response_score': 'Competitive response',
    'dynamic_range_raw_score': 'Dynamic range raw',
    'dynamic_range_score': 'Dynamic range',
    'repeatability_score': 'Repeatability',
    'background_quality_score': 'Background quality',
    'reference_stability_score': 'Reference stability',
    'total_score': 'Total score',
}


TABLE_LABELS = {
    'experiments': 'Experiments',
    'strip_results': 'Strip results',
    'upload_records': 'Upload records',
    'upload_meta': 'Upload metadata',
    'reagent_lots': 'Reagent lots',
    'pad_material': 'Pad materials',
    'conjugate_batch': 'Conjugate batches',
}


def display_label(name):
    text = str(name or '').strip()
    if text in FIELD_LABELS:
        return FIELD_LABELS[text]
    return text.replace('_', ' ').strip().title()


def table_label(name):
    text = str(name or '').strip()
    return TABLE_LABELS.get(text, display_label(text))


def label_with_required(name, required=False):
    label = display_label(name)
    return f'{label} *' if required else label
